Updated setups.h based on Python version change from 3.8 to 3.9 in the CloudIDE lab environment
ibm-developer-skills-network/aolwx-devops-capstone-template pull request #12
Opened 2023-12-18 10:17 UTC by Sklup55

Updated setup.sh based on Python version change from 3.8 to 3.9 in the CloudIDE lab environment

2023-12-18 12:48 UTC, rofrano requested changes
Unless there is a good reason for line 13 to install python 3.10 venv, please remove that line. It doesn't seem to be needed since Pythion 3.9 venv is installed on line 8.

2023-12-18 12:48 UTC, rofrano commented on bin/setup.sh
> +sudo apt install python3.10-venv
Why is this `python3.10-venv` install here? You installed `python3.9-venv` on line 8?

2023-12-19 08:22 UTC, Sklup55 commented on bin/setup.sh
> +sudo apt install python3.10-venv
Thanks a lot for your insights; we have noted them & tested as per that;
I am cancelling this one & sending a new Pull request

2023-12-19 08:22 UTC, closed without merging

2023-12-19 13:25 UTC, rofrano commented on bin/setup.sh
> +sudo apt install python3.10-venv
@Sklup55 A Pull Request is a "living" document. There was no need to create another one. That looses the conversation which is a bad thing. In the future just update your branch and push it to GitHub and use the same Pull Request so that all of the comment are not lost. The same Pull Request will pick up the new code because the Pull Request is against the branch not the state of the code.

I've approved your new Pull Request.

2023-12-20 05:38 UTC, Sundar-05 commented on bin/setup.sh
> +sudo apt install python3.10-venv
@rofrano  I apologize for the inconvenience caused.  Thank you for explaining the details & process !  I  will make a note of this & follow in future!

2023-12-20 05:44 UTC, Sklup55 commented on bin/setup.sh
> +sudo apt install python3.10-venv
@rofrano
I apologize for the inconvenience caused. Thank you for explaining the details & process so clearly! I will follow this hereafter!

Thank you for approving the Pull request!

2023-12-20 13:43 UTC, rofrano commented on bin/setup.sh
> +sudo apt install python3.10-venv
@Sklup55 No worries. Just pointing it out for next time. :)